name: Gen_Filters_And_Cache

env:
  DEFAULT_KEY: ${{ secrets.DEV_CACHER_DEFAULT_KEY }} # Azure Functions default API Key for Redis-cacher

on:
  workflow_dispatch:
  push:
    paths-ignore: 
      - '**/README.md' # don't run on README.rst file updates anywhere in repo
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: 'IATI-Standard-SSOT/requirements.txt'

      - name: "Generate Filters"
        run: ./genFilters.sh

      - name: "Check Results"
        run: |
          ls -lah *.json

      - name: 'Setup git config'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: 'Commit changes'
        run: |
          RESP=$(git add *.json -v)
          if [[ $RESP == "" ]]; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "updated by GitHub Actions workflow"
            git push origin develop
          fi
